### ISSUE TITLE
English typo in merge.py

### ISSUE THREAD

**Issue by AndreaPi** [AILAB-bh/cocohelper#12]
**Describe the bug**
English typo on line 25 of `merge.py` https://github.com/AILAB-bh/cocohelper/blob/2af95b7cd456a6cfe5df68afbb465845366dbefc/src/cocohelper/merge.py#L25: 

**To Reproduce**
N/A

**Expected behavior**
```
    if len(coco_helpers) < 2:
        raise ValueError("The minimum number of coco helpers that can be merged is 2. Please feed two or more "
                         "COCOHelper objects.")
```

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Comment by valvgab-bh** [comment]
closed in #26
