### ISSUE TITLE
Unit test missing for function merge_coco in module merge.py

### ISSUE THREAD

**Issue by AndreaPi** [AILAB-bh/cocohelper#13]
**Describe the bug**
Issue #11 suggests that there's no unit test for the function `merge_coco()` in  [merge.py](https://github.com/AILAB-bh/cocohelper/blob/master/src/cocohelper/merge.py). Indeed, by looking at [test_merger.py](https://github.com/AILAB-bh/cocohelper/blob/master/tests/unit/test_cocohelper/test_merger.py) it's easy to verify that there's no unit test for `merge_coco()`.

**To Reproduce**
N/A

**Expected behavior**
Add unit test for `merge_coco()` in [test_merger.py](https://github.com/AILAB-bh/cocohelper/blob/master/tests/unit/test_cocohelper/test_merger.py)

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

cc @valvgab-bh

**Comment by andreap-bh** [comment]
Unit test found, closing issue
